### PR TITLE
Optional properties syntax

### PR DESCRIPTION
**Pull request by matjaz**

### CODE REVIEW

**Comment by mckoss** [comment]
Thanks for this PR.  However, I was hoping to leave ? out of the language - I prefer the more explicit:

prop: Type | null

syntax.

Your thoughts?

**Comment by matjaz** [comment]
I prefer to type less :)

**Comment by mckoss** [comment]
I can appreciate the desire for brevity - and the alignment with TypeScript is compelling (I also note the similar annotation in Closure Compiler ?type - for nullable types).

In my experience with Closure Compiler, I found this annotation to be confusing in the long run.   People sometimes did not know what it meant, and would often include it for the wrong reasons.  The more explicit type expression "Type | null" is unambiguous, explicit, and deliberate.  So, in my mind, that trumps saving a few characters of typing.

We have several of us working on this language design at Google - I'll invite them to chime in on this discussion as well  This PR is likely not going to be approved right away until we reach a consensus.

**Comment by TristonianJones** [comment]
With respect to the Closure Compiler, I have to agree that the `?` to indicate an optional parameter is a common source of bugs. However, part of why I think it's a common source of bugs is because sometimes a value can be nullable without specifying `?`.

TypeScript and Swift have also adopted the operator and appear to be using it more consistently, so perhaps this is becoming a more common pattern and the difficulty of knowing when to use it has diminished. Although in Swift the `?` is at the end of the statement which I think is a bit more human readable.

Here are the conventions I've encountered for expressing an optional value (sometimes in a type, sometimes only as a parameter)

Language | Nullable Convention
------------- | --------------
Closure | `@type {?primitive}`, `@type {OptType}`, `@type {OptType|null}`, `@type {?OptType}`, `@type {primitive|null}`
C++/C# | `type param = default_value`
Java | `@Nullable` or method overload (or just pass `null` and don't error!)
SQL | nullable by default, unless `NOT NULL`
Swift | `var name: type?`
TypeScript | `name?: type`

What's notable is that there are five ways of saying the same thing in Closure. In many cases the more powerful expression is Closure is the `!` which indicates a value must not be null. SQL takes this stance as well, but I think this can often disguise issues where a field isn't set that should be.

Any objection to putting the `?` at the end of the type? I realize it's less TypeScript like, but truthfully either Swift or TypeScript style here is fine with me so long as there is only one way to specify that a value may be `null`.

**Comment by matjaz** [comment]
Bolt language already support null type using multiple types.
```
type Test {
  a?: number // nullable using ?
  b: number|null // number or null type
}
```

As I already said, coming from TypeScript syntax it felt naturally to me to add `?` syntax, just to type less. :)

**Comment by tomlarkworthy** [comment]
"Type | null" is a union type, but null is not really a type so I don't think that makes sense.
"name ?: Type" is an optional variable, more analogous to "undefined | Type". So in Firebase, a null value is the same as a not-specified value, hence the distinction is not all that important, however a future model, or a code generator, might make the distinction. So there is a few different decisions

1. can you explicitly set a value of null to an optional property (not important for core Firebase, but important downstream), ie. is obj.optional = null a validation error or not?
2. If a property is not specified as optional, can you set it to null? 

In Java everything can be set to null, null is a universal value that can fit in any type. Its the cause of many bugs and I think developments like Swift are showing mainstream desire to sort the problem out.

I agree with Tristan. Its only important to have optional types if we have a different behaviour if it is not set as optional. There are two paths 

1. have optional properties, implying the default (non-optional) behavior is strictly excluding undefined behavior (although there is wiggle room for explicitly setting the value as null)
2. have required properties, implying the default behavior of properties.

Firebase is NoSQL. So I think philosophically it should be looser by default, which suggests explicit opt-in to required properties (2) over of optional properties (1).  

If we had a model where we wanted to allow null assignment to required fields I would suggest

field : Type     //optional field,  not specified or a not-null value 
field ?: Type   //optional field,  not specified or a null or a value (an optional Maybe)
field !: Type    //required field, must be specified and cannot be null
field !?: Type  //required field, can be set to null (but must always be specified)  (a required Maybe)

If we adopted the above and then build a code generator, the simplest notation field: Type would end up to a Maybe<NotNullType>, which I think is generally what I think we would want. 

To summerize, in short term I would not have optional types, and would go for explicit required types instead with something like !

**Comment by matjaz** [comment]
Setting a value to `null` in FB removes a field. So there can not be fields with null value.

Opinion on null value http://www.yegor256.com/2014/05/13/why-null-is-bad.html

**Comment by mckoss** [comment]
One thing that is confusing is different default behavior for "primitive" vs. "compound" types.  Since types like string, number are default "not nullable", I think all types should be default "no nullable".  I prefer the explicit

    Type | null

or

    Type | Null to be more correct with the type system

is better than

    Type?

**Comment by tomlarkworthy** [comment]
Very good point about complex types. Capital Null makes more sense in that
notation.

So your suggesting required by default. I personally think that's the wrong
way round for a nosql RAD language.

**Comment by mckoss** [comment]
The counter argument (in favor of default required types) is that it is the "safer" default - when users are surprised, it's when they are writing objects with missing data (as opposed to being surprised that a schema they thought they were mandating is actually allowing optional values).

**Comment by tomlarkworthy** [comment]
Yes that's a totally reasonable position, if the underlying design philosophy of Bolt is "safe-by-default".

**Comment by matjaz** [comment]
Agree with @mckoss. We're talking about security rules here and be more stricter is preferred (safe by default).
It also nicely aligns with Firebase functions and current implementation (eg. `newData.child('prop').isString()` and for optional just add `|| newData.child('prop') == null`).

**Comment by TristonianJones** [comment]
Safe by default sounds good to me. Mike stated this more succinctly than I did. My oblique reference to `!` being a source of bugs where a field should have been set that wasn't was my attempt at saying the same.

I was also suggesting that we should only have one way of specifying nullabilty (in the SQL sense which is more like undefined). Either the union type with `Null` or the `?` but not both. In the SQL sense `null` isn't a type, so allowing it in the union is slightly odd even if this is what Closure allows.

**Comment by mckoss** [comment]
I'm closing this as I think we have consensus that Type | Null is the preferred method of expression, and we don't want multiple ways to express optionality of a property.

**Comment by TristonianJones** [comment]
After a bit more thought I have a couple of concerns.

1 - `Null` is a keyword masquerading as a type. In theory anything in the union that looks like a type ought to be a type. This would seem to imply the following is possible (which is odd):
```
type MyType extends Null {}
```

2 - In most languages `null` is a value, but in SQL `null` is synonymous with `undefined` or not set. Is this feature aimed at addressing `undefined` or whether a defined property can be set to `null`? I believe these are two different concepts. As we have been discussing the approaches thus far, we've been speaking in the following terms

`Type?` - property value is Type, or not set, or set to null
`{Type | Null}` - property value is Type or Null (which also implies not set)

Is there a case where if the field is set it must be a non-null `Type` value? Or, as a slight variation a case where a field must be set and one of the values it could be set to was null? If so the two operators could be combined without any overlap in meaning (assuming we switch to a `null` keyword again).

`Type?` - property value is Type, or not set.
`{Type | null}` - property value is Type or null, required to be set.
`{Type | null}?` - property value is Type or null, optionally set.

Using both operators in this way is more precise, although more nuanced. If we just use the union type, then we should introduce `undefined` as a keyword such that the following may be expressed

`{Type | null | undefined}` - property value is Type or null or not set.

**Comment by matjaz** [comment]
I would go with just `Type?`. Meaning value is set to non null (scalar, object) value or not set.
In languages that does not have concept of "not set" (undefined) value would be set to null.

**Comment by TristonianJones** [comment]
Should `null` and `undefined` be interchangeable? I think the answer is no. The following expressions are safe by default:
```
!null // equals true
!undefined // should equal undefined
``` 
JavaScript is not safe by default as `!undefined == true`. The rule compiler should expand the check to permit undefined values only if the developer has indicated this is expected.

**Comment by tomlarkworthy** [comment]
Hmm, maybe we get rid of null as a keyword and just have undefined?

**Comment by mckoss** [comment]
I'd like to close this PR.  Our current implementation is a Null type for optional properties.  I'm fine with that myself.  If there is a proposal for something different, let's move that to an issue, and not have the dicsussion in this (closed) PR.  Thanks!

**Pull request closed without merging**
