### PR TITLE
 Add TS type

### PR DESCRIPTION
**Pull request by wcandillon**

### CODE REVIEW

**Comment by andrioli** [comment]
I'm using firebase-bolt as a library in my TS project. This will be pretty useful 😄. You guys are planning to release the package with types in a future release?

**Comment by rockwotj** [comment]
@andrioli I'm not super familiar with publishing types, does this PR does everything for this to happen?

@wcandillon Can you update this PR and sign the CLA? Until then I can't merge this.

**Comment by wcandillon** [comment]
I signed it!

**Comment by rockwotj** [comment]
@wcandillon can you merge master into your fork? The build needs to pass as well

**Comment by andrioli** [comment]
@rockwotj As far as I know, publishing the package with types definition (`.d.ts` extension) is all it's needed. The option `declaration` included by @wcandillon will generate these files automatically. See the option description [here](https://www.typescriptlang.org/docs/handbook/compiler-options.html).

**Comment by rockwotj** [comment]
@andrioli I understand that would help, and I want to merge this, but the Travis CI must pass. All @wcandillon needs to do is merge with master and the build will pass.

**Comment by andrioli** [comment]
@rockwotj @wcandillon If you prefer I can create another PR based in this one (with all checks green)

**Comment by rockwotj** [comment]
@andrioli I'm fine with it.

**Comment by wcandillon** [comment]
@rockwotj @andrioli Just merged master in this PR, thks a lot!

**Comment by rockwotj** [comment]
The build is still failing, does this build for you locally?

**Comment by rockwotj** [comment]
Closing this in favor of #227

**Pull request closed without merging**
